### PR TITLE
updates to 2014-03-17-uw bootcamp page

### PR DESCRIPTION
**Pull request by LJWilliams**

### CODE REVIEW

**Comment by wking** [comment]
On Sun, Mar 02, 2014 at 02:16:31PM -0800, Lynne Williams wrote:

> - updated setup information and started to add python module to topics

The id for the linux-sqlite.html should be “setup-linux-sqlite”, not
“setup-windows-sqlite”.  I think it's probably a good idea to point
people to their package managers here, because it's hard to imagine a
distrinbution that doesn't package SQLite.  Package names on common
distro families:
- Debian: sqlite3 (https://packages.debian.org/stable/sqlite3)
- Fedora: sqlite (https://apps.fedoraproject.org/packages/sqlite)
- Gentoo: dev-db/sqlite (http://gpo.zugaina.org/dev-db/sqlite)

> - adding link to R syllabus

This is linking into http://ljwilliams.github.io/2014-03-17-uw/, but
since this PR is for the swcarpentry repository, I think it should be
http://swcarpentry.github.io/2014-03-17-uw/.

> - changing the height of the eventbrite registration box to accomodate R session (Hopefully this will bring more people into the R room)
> 
> -- File Changes --
> 
> ```
> M _includes/bootcamps/eventbrite.html (2)
> A _includes/schedule.html (90)
> M _includes/setup/linux-bash.html (2)
> M _includes/setup/linux-editor.html (2)
> M _includes/setup/linux-git.html (2)
> M _includes/setup/linux-python.html (2)
> A _includes/setup/linux-sqlite.html (12)
> M _includes/setup/macosx-bash.html (2)
> M _includes/setup/macosx-editor.html (2)
> M _includes/setup/macosx-git.html (6)
> M _includes/setup/macosx-python.html (2)
> A _includes/setup/macosx-sqlite.html (15)
> A _includes/setup/overview-sqlite.html (8)
> M _includes/setup/windows-bash.html (2)
> M _includes/setup/windows-editor.html (2)
> M _includes/setup/windows-git.html (2)
> M _includes/setup/windows-python.html (2)
> M _includes/setup/windows-sqlite.html (2)
> M index.html (42)
> A lessons/r/intermediate/01_countrySpecificInterceptSlope.R (28)
> A lessons/r/intermediate/02_slopeComparisonAsiaVsAmericas.R (34)
> A lessons/r/intermediate/Makefile.r (7)
> A lessons/r/intermediate/gapminderDataFiveYear.txt (1705)
> A lessons/r/intermediate/index.md (76)
> A lessons/r/intermediate/r-setup.md (79)
> A lessons/r/intermediate/session01_postProject.R (38)
> A lessons/r/intermediate/session01_preProject.R (59)
> A lessons/r/intermediate/session01_toyLine.R (26)
> A lessons/r/intermediate/session02_careFeedingData.R (215)
> A lessons/r/intermediate/session04_ggplot2.r (142)
> A lessons/r/intermediate/session07_dataAggregation.r (94)
> A lessons/r/intermediate/session08_file-io.r (64)
> A lessons/r/intermediate/session08_pipeline.r (83)
> ```
> 
> -- Patch Links --
> 
> https://github.com/swcarpentry/2014-03-17-uw/pull/1.patch
> https://github.com/swcarpentry/2014-03-17-uw/pull/1.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/swcarpentry/2014-03-17-uw/pull/1

## 

This email may be signed or encrypted with GnuPG (http://www.gnupg.org).
For more information, see http://en.wikipedia.org/wiki/Pretty_Good_Privacy

**Comment by LJWilliams** [comment]
Thanks Trevor

**Comment by wking** [comment]
I see that this PR has grown a few more commits, but is still not
merged to the live gh-pages branch.  We should probably merge it soon,
or students won't get the new setup information.  The new commits look
fine to me, with the exception of a “sqlit” (instead of “sqlite” typo
in 38b1259 (changing setup instructions for SQLite for Linux,
2014-04-02.  However, I think we're at the stage where we should just
be pushing to gh-pages, and fixing stuff on the fly as we notice it.

**Comment by LJWilliams** [comment]
Hi Trevor.  The bootcamp site now points to my repo, so the changes are live.  Feel free to make any changes to the python page that you want/need.

Lynne

**Comment by jennybc** [comment]
This lack of clarity around where the UW bootcamp web material lives is confusing me. And could easily confuse students.

Is our "master" website here:
http://ljwilliams.github.io/2014-03-17-uw/

or here:
http://swcarpentry.github.io/2014-03-17-uw/

It would be best to make the non-master cease to exist. I'd like to know where to put updated R set-up instructions and I can't tell.

Also @LJWilliams do you want us to make edits or pull requests?

**Comment by LJWilliams** [comment]
The site linked to the swc bootcamp page is at http://ljwilliams.github.io/2014-03-17-uw/. Christina had problems with pushing directly into my repo for the last bootcamp, so if you could do pull requests it would be appreciated.

Thanks everyone,

Lynne

**Pull request closed without merging**
